import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import StoreContextProvider from "./contexts/StoreContext";
import PageOrLoading from "./PageOrLoading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="portal-root"></div>
        <Toaster position="top-center" />
        <StoreContextProvider>
          <div className="min-w-screen min-h-screen flex flex-col overflow-x-hidden">
            <PageOrLoading>{children}</PageOrLoading>
            {/* <Header />
            <div className="flex h-full flex-1 ">
              <SideMenu />
              {children}
            </div> */}
          </div>
        </StoreContextProvider>
      </body>
    </html>
  );
}
